export const REGISTERING = "REGISTERING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGGING_IN = "LOGGING_IN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SENDING_RECOVERY_EMAIL = "SENDING_RECOVERY_EMAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const RESETTING_PASSWORD = "RESETTING_PASSWORD";
export const RESET_SUCCESS = "RESET_SUCCESS";
export const RESET_FAILURE = "RESET_FAILURE";

export const CHANGING_EMAIL = "CHANGING_EMAIL";
export const CHANGE_EMAIL_SUCCESS = "CHANGE_EMAIL_SUCCESS";
export const CHANGE_EMAIL_FAILURE = "CHANGE_EMAIL_FAILURE";

export const CHANGING_PASSWORD = "CHANGING_PASSWORD";
export const CHANGE_PW_SUCCESS = "CHANGE_PW_SUCCESS";
export const CHANGE_PW_FAILURE = "CHANGE_PW_FAILURE";

export const ADDING_PROGRESS = "ADDING_PROGRESS";
export const ADD_PROGRESS_SUCCESS = "ADD_PROGRESS_SUCCESS";
export const ADD_PROGRESS_FAILURE = "ADD_PROGRESS_FAILURE";

export const FETCHING_PROGRESS = "FETCHING_PROGRESS";
export const FETCH_PROGRESS_SUCCESS = "FETCH_PROGRESS_SUCCESS";
export const FETCH_PROGRESS_FAILURE = "FETCH_PROGRESS_FAILURE";

export const DELETE_PROGRESS = "DELETE_PROGRESS";

export const FETCHING_ROUTINES = "FETCHING_ROUTINES";
export const FETCH_ROUTINES_SUCCESS = "FETCH_ROUTINES_SUCCESS";
export const FETCH_ROUTINES_FAILURE = "FETCH_ROUTINES_FAILURE";

export const SELECT_ROUTINE = "SELECT_ROUTINE";

export const FETCHING_ROUTINE_HISTORY = "FETCHING_ROUTINE_HISTORY";
export const FETCH_ROUTINE_HISTORY_SUCCESS = "FETCH_ROUTINE_HISTORY_SUCCESS";
export const FETCH_ROUTINE_HISTORY_FAILURE = "FETCH_ROUTINE_HISTORY_FAILURE";

export const POSTING_NEW_ROUTINE = "POSTING_NEW_ROUTINE";
export const POST_NEW_ROUTINE_SUCCESS = "POST_NEW_ROUTINE_SUCCESS";
export const POST_NEW_ROUTINE_FAILURE = "POST_NEW_ROUTINE_FAILURE";

export const POSTING_NEW_EXERCISE_IN_ROUTINE =
  "POSTING_NEW_EXERCISE_IN_ROUTINE";
export const POST_NEW_EXERCISE_IN_ROUTINE_SUCCESS =
  "POST_NEW_EXERCISE_IN_ROUTINE_SUCCESS";
export const POST_NEW_EXERCISE_IN_ROUTINE_FAILURE =
  "POST_NEW_EXERCISE_IN_ROUTINE_FAILURE";

export const UPDATING_EXERCISE = "UPDATING_EXERCISE";
export const UPDATE_EXERCISE_SUCCESS = "UPDATE_EXERCISE_SUCCESS";
export const UPDATE_EXERCISE_FAILURE = "UPDATE_EXERCISE_FAILURE";

export const UPDATING_ROUTINE = "UPDATING_ROUTINE";
export const UPDATE_ROUTINE_SUCCESS = "UPDATE_ROUTINE_SUCCESS";
export const UPDATE_ROUTINE_FAILURE = "UPDATE_ROUTINE_FAILURE";

export const SCHEDULING_WORKOUT = "SCHEDULING_WORKOUT";
export const SCHEDULE_WORKOUT_SUCCESS = "SCHEDULE_WORKOUT_SUCCESS";
export const SCHEDULE_WORKOUT_FAILURE = "SCHEDULE_WORKOUT_FAILURE";
export const FETCHING_WORKOUTS = "FETCHING_WORKOUTS";
export const FETCH_WORKOUTS_SUCCESS = "FETCH_WORKOUTS_SUCCESS";
export const FETCH_WORKOUTS_FAILURE = "FETCH_WORKOUTS_FAILURE";
export const DELETE_WORKOUT = "DELETE_WORKOUT";

export const FETCHING_CHECKOFF_ITEMS = "FETCHING_CHECKOFF_ITEMS";
export const FETCH_CHECKOFF_ITEMS_SUCCESS = "FETCH_CHECKOFF_ITEMS_SUCCESS";
export const FETCH_CHECKOFF_ITEMS_FAILURE = "FETCH_CHECKOFF_ITEMS_FAILURE";

export const UPDATING_PROGRESS = "UPDATING_PROGRESS";
export const UPDATE_PROGRESS_SUCCESS = "UPDATE_PROGRESS_SUCCESS";
export const UPDATE_PROGRESS_FAILURE = "UPDATE_PROGRESS_FAILURE";


export const PROCESSING_PAYMENT = "PROCESSING_PAYMENT";
export const PAYMENT_SUCCESS = "PAYMENT SUCCESS";
export const PAYMENT_FAILURE = "PAYMENT FAILURE";
