export const REGISTERING = "REGISTERING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGGING_IN = "LOGGING_IN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const SENDING_RECOVERY_EMAIL = "SENDING_RECOVERY_EMAIL";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const CHANGING_PASSWORD = "RESETTING_PASSWORD";
export const CHANGE_SUCCESS = "CHANGE_SUCCESS";
export const CHANGE_FAILURE = "CHANGE_FAILURE";

export const ADDING_PROGRESS = "ADDING_PROGRESS";
export const ADD_PROGRESS_SUCCESS = "ADD_PROGRESS_SUCCESS";
export const ADD_PROGRESS_FAILURE = "ADD_PROGRESS_FAILURE";

export const FETCHING_PROGRESS = "FETCHING_PROGRESS";
export const FETCH_PROGRESS_SUCCESS = "FETCH_PROGRESS_SUCCESS";
export const FETCH_PROGRESS_FAILURE = "FETCH_PROGRESS_FAILURE";

export const DELETE_PROGRESS = "DELETE_PROGRESS";

